[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "."

[functions]
  directory = "."
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
